version: "3.7"
services:
  # Web service layer
  django:
    build:
      context: .
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      GOOGLE_GEOCODING_API_KEY: 123.456
    ports:
      - "8000:8000"
    volumes:
      - "./:/opt/reprohack/"

  # Data persistence service layer
  db:
    image: mariadb:10.5-bionic
    environment:
      MYSQL_ROOT_PASSWORD: 123.456
      MYSQL_DATABASE: reprohack
    volumes:
      - "db_data:/var/lib/mysql"
    ports:
      - "3306:3306"

volumes:
  db_data:
